# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'
tasks:
  default: echo "$(cat '{{.TASKFILE}}')"
  
  init:
    desc: 'create standart nuxt app'
    internal: false
    cmds:
    - bun --bun create nuxt src

  upgrade:
    desc: 'install and update'
    internal: false
    dir : '{{.TASKFILE_DIR}}/../src'
    cmds:
    - bunx --bun nuxi@latest upgrade
    - bun  --bun install
    - bun  --bun update --latest

  folders:
    desc: 'create folders'
    internal: false
    dir : '{{.TASKFILE_DIR}}'
    cmds:
    - cp -r ./folders/* ./../src

  install-modules:
    desc: 'install modules'
    internal: false
    dir : '{{.TASKFILE_DIR}}/../src'
    cmds:
    - bunx --bun nuxi@latest module add pinia
    - bunx --bun nuxi@latest module add vueuse
    - bun  --bun update --latest

  config:
    desc: 'create folders'
    internal: false
    dir : '{{.TASKFILE_DIR}}/../src'
    cmds:
    - mv config/nuxt.config.mjs nuxt.config.ts
    - rm -rf config
  
  x:
    desc: 'exec all'
    cmds:
    - task: init
    - task: upgrade
    - task: folders
    - task: install-modules
    - task: config

  z:
    desc: 'delete the created project'
    dir : '{{.TASKFILE_DIR}}/..'
    cmds:
    - rm -rf  src